# Generated by Django 6.0.3 on 2026-04-07 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='default_downloadquota',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='default_downloadrate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='default_redirurl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='default_sessionlength',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='asset',
            name='default_uploadquota',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='default_uploadrate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='supported_ad_types',
            field=models.CharField(blank=True, default='IMAGE,VIDEO', help_text='Comma separated values like IMAGE,VIDEO', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='supported_ratio',
            field=models.CharField(blank=True, help_text='Example: 16:9, 9:16, 1:1', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='review_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ManagerAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CAMPAIGN_APPROVED', 'Campaign Approved'), ('CAMPAIGN_REJECTED', 'Campaign Rejected'), ('CAMPAIGN_PAUSED', 'Campaign Paused'), ('CAMPAIGN_RESUMED', 'Campaign Resumed'), ('AD_APPROVED', 'Ad Approved'), ('AD_REJECTED', 'Ad Rejected'), ('AD_PAUSED', 'Ad Paused'), ('AD_RESUMED', 'Ad Resumed'), ('PLACEMENT_APPROVED', 'Placement Approved'), ('PLACEMENT_REJECTED', 'Placement Rejected'), ('PLACEMENT_PAUSED', 'Placement Paused'), ('PLACEMENT_RESUMED', 'Placement Resumed')], max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ads.ad')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ads.campaign')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads_manager_actions', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ads.placement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
