"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import environ

# --------------------------------------------------
# Base directory
# --------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------------------------------
# Environment variables
# --------------------------------------------------
env = environ.Env(
    DEBUG=(bool, True),
)

# Optional: load .env file if present
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# --------------------------------------------------
# Core settings
# --------------------------------------------------
SECRET_KEY = env(
    "SECRET_KEY",
    default="django-insecure-change-this-in-production"
)

DEBUG = env.bool("DEBUG", default=True)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[
    "127.0.0.1",
    "localhost",
    ".wiadspot.local",   # allows partner.wiadspot.local, admin.wiadspot.local, etc.
    "wiadspot.com",
    "www.wiadspot.com",
    "partner.wiadspot.com",
    "clients.wiadspot.com",
    "ads.wiadspot.com",
    "admin.wiadspot.com",
    "client.wiadspot.com",
    "owner.wiadspot.com",
    "manager.wiadspot.com",
])

# Django accepts same-origin requests by default; do not trust sibling hosts.
CSRF_TRUSTED_ORIGINS = []

# --------------------------------------------------
# MSG91 settings
# --------------------------------------------------
MSG91_AUTHKEY = env("MSG91_AUTHKEY", default="")
MSG91_TEMPLATE_ID = env("MSG91_TEMPLATE_ID", default="")
MSG91_TIMEOUT = env.int("MSG91_TIMEOUT", default=15)
MSG91_OTP_EXPIRY = env.int("MSG91_OTP_EXPIRY", default=10)

MSG91_SEND_OTP_URL = env(
    "MSG91_SEND_OTP_URL",
    default="https://control.msg91.com/api/v5/otp"
)
MSG91_RETRY_OTP_URL = env(
    "MSG91_RETRY_OTP_URL",
    default="https://control.msg91.com/api/v5/otp/retry/{request_id}"
)
MSG91_VERIFY_OTP_URL = env(
    "MSG91_VERIFY_OTP_URL",
    default="https://control.msg91.com/api/v5/otp/verify/{request_id}/{otp}"
)

FAS_KEY = env(
    "FAS_KEY",default=""
)

# --------------------------------------------------
# Application definition
# --------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "core",
    "website",
    "partner",
    "clients",
    "ads",
    "dashboard_admin",
    # "website",   # add this if you create an app for www.wiadspot.com
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "config.middleware.SubdomainURLRoutingMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.site_links",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# --------------------------------------------------
# Database
# --------------------------------------------------
DATABASES = {
    "default": env.db(
        "DATABASE_URL",
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
    )
}

# --------------------------------------------------
# Password validation
# --------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# --------------------------------------------------
# Internationalization
# --------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Dubai"
USE_I18N = True
USE_TZ = True

# --------------------------------------------------
# Static files
# --------------------------------------------------
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = Path(env("STATIC_ROOT", default=str(BASE_DIR / "staticfiles")))

# --------------------------------------------------
# Media files
# --------------------------------------------------
MEDIA_URL = "/media/"
MEDIA_ROOT = Path(env("MEDIA_ROOT", default=str(BASE_DIR / "media")))

# --------------------------------------------------
# Authentication redirects
# --------------------------------------------------
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"

# --------------------------------------------------
# Default primary key type
# --------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Each workspace signs in independently. Never share cookies across subdomains.
SESSION_COOKIE_DOMAIN = None
CSRF_COOKIE_DOMAIN = None
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

# --------------------------------------------------
# Security settings for production
# --------------------------------------------------
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
# Only Nginx can reach the loopback-bound application server.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
